// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/eduflow-bold/BoldGradient.tsx": () => import("../components/mockups/eduflow-bold/BoldGradient.tsx"),
  "./components/mockups/eduflow-clean/CleanLight.tsx": () => import("../components/mockups/eduflow-clean/CleanLight.tsx"),
  "./components/mockups/eduflow-dark/ModernDark.tsx": () => import("../components/mockups/eduflow-dark/ModernDark.tsx")
};
